DELIMITER ;

USE atlbeltline;

CALL register_user("james.smith", "jsmith123", "James", "Smith", 0 );
CALL manage_user("james.smith", "APPROVED" );
CALL register_user("michael.smith", "msmith456", "Michael", "Smith", 1 );
CALL manage_user("michael.smith", "APPROVED" );
CALL register_user("robert.smith", "rsmith789", "Robert ", "Smith", 0 );
CALL manage_user("robert.smith", "APPROVED" );
CALL register_user("maria.garcia", "mgarcia123", "Maria", "Garcia", 1 );
CALL manage_user("maria.garcia", "APPROVED" );
CALL register_user("david.smith", "dsmith456", "David", "Smith", 0 );
CALL manage_user("david.smith", "APPROVED" );
CALL register_user("manager1", "manager1", "Manager", "One", 0 );
CALL register_user("manager2", "manager2", "Manager", "Two", 1 );
CALL manage_user("manager2", "APPROVED" );
CALL register_user("manager3", "manager3", "Manager", "Three", 0 );
CALL manage_user("manager3", "APPROVED" );
CALL register_user("manager4", "manager4", "Manager", "Four", 1 );
CALL manage_user("manager4", "APPROVED" );
CALL register_user("manager5", "manager5", "Manager", "Five", 1 );
CALL manage_user("manager5", "APPROVED" );
CALL register_user("maria.rodriguez", "mrodriguez", "Maria", "Rodriguez", 1 );
CALL manage_user("maria.rodriguez", "DENIED" );
CALL register_user("mary.smith", "msmith789", "Mary", "Smith", 1 );
CALL manage_user("mary.smith", "APPROVED" );
CALL register_user("maria.hernandez", "mhernandez", "Maria", "Hernandez", 1 );
CALL manage_user("maria.hernandez", "APPROVED" );
CALL register_user("staff1", "staff1234", "Staff", "One", 0 );
CALL manage_user("staff1", "APPROVED" );
CALL register_user("staff2", "staff4567", "Staff", "Two", 1 );
CALL manage_user("staff2", "APPROVED" );
CALL register_user("staff3", "staff7890", "Staff", "Three", 1 );
CALL manage_user("staff3", "APPROVED" );
CALL register_user("user1", "user123456", "User", "One", 0 );
CALL register_user("visitor1", "visitor123", "Visitor", "One", 1 );
CALL manage_user("visitor1", "APPROVED" );

CALL add_email("james.smith", "jsmith@gmail.com" );
CALL add_email("james.smith", "jsmith@hotmail.com" );
CALL add_email("james.smith", "jsmith@gatech.edu" );
CALL add_email("james.smith", "jsmith@outlook.com" );
CALL add_email("michael.smith", "msmith@gmail.com" );
CALL add_email("robert.smith", "rsmith@hotmail.com" );
CALL add_email("maria.garcia", "mgarcia@yahoo.com" );
CALL add_email("maria.garcia", "mgarcia@gatech.edu" );
CALL add_email("david.smith", "dsmith@outlook.com" );
CALL add_email("maria.rodriguez", "mrodriguez@gmail.com" );
CALL add_email("mary.smith", "mary@outlook.com" );
CALL add_email("maria.hernandez", "mh@gatech.edu" );
CALL add_email("maria.hernandez", "mh123@gmail.com" );
CALL add_email("manager1", "m1@beltline.com" );
CALL add_email("manager2", "m2@beltline.com" );
CALL add_email("manager3", "m3@beltline.com" );
CALL add_email("manager4", "m4@beltline.com" );
CALL add_email("manager5", "m5@beltline.com" );
CALL add_email("staff1", "s1@beltline.com" );
CALL add_email("staff2", "s2@beltline.com" );
CALL add_email("staff3", "s3@beltline.com" );
CALL add_email("user1", "u1@beltline.com" );
CALL add_email("visitor1", "v1@beltline.com" );

INSERT INTO Employee VALUES("james.smith", "000000001", "4043721234", "123 East Main Street", "Rochester", "NY", "14604", 1);
CALL register_employee_aft("michael.smith", "000000002", "4043726789", "350 Ferst Drive", "Atlanta", "GA", "30332", "STAFF" );
CALL register_employee_aft("robert.smith", "000000003", "1234567890", "123 East Main Street", "Columbus", "OH", "43215", "STAFF" );
CALL register_employee_aft("maria.garcia", "000000004", "7890123456", "123 East Main Street", "Richland", "PA", "17987", "MANAGER" );
CALL register_employee_aft("david.smith", "000000005", "5124776435", "350 Ferst Drive", "Atlanta", "GA", "30332", "MANAGER" );
CALL register_employee_aft("manager1", "000000006", "8045126767", "123 East Main Street", "Rochester", "NY", "14604", "MANAGER" );
CALL register_employee_aft("manager2", "000000007", "9876543210", "123 East Main Street", "Rochester", "NY", "14604", "MANAGER" );
CALL register_employee_aft("manager3", "000000008", "5432167890", "350 Ferst Drive", "Atlanta", "GA", "30332", "MANAGER" );
CALL register_employee_aft("manager4", "000000009", "8053467565", "123 East Main Street", "Columbus", "OH", "43215", "MANAGER" );
CALL register_employee_aft("manager5", "000000010", "8031446782", "801 Atlantic Drive", "Atlanta", "GA", "30332", "MANAGER" );
CALL register_employee_aft("staff1", "000000011", "8024456765", "266 Ferst Drive Northwest", "Atlanta", "GA", "30332", "STAFF" );
CALL register_employee_aft("staff2", "000000012", "8888888888", "266 Ferst Drive Northwest", "Atlanta", "GA", "30332", "STAFF" );
CALL register_employee_aft("staff3", "000000013", "3333333333", "801 Atlantic Drive", "Atlanta", "GA", "30332", "STAFF" );
	
CALL create_site("Piedmont Park", "30306", "400 Park Drive Northeast", "manager2", 1 );
CALL create_site("Atlanta Beltline Center", "30307", "112 Krog Street Northeast", "manager3", 0 );
CALL create_site("Historic Fourth Ward Park", "30308", "680 Dallas Street Northeast", "manager4", 1 );
CALL create_site("Westview Cemetery", "30310", "1680 Westview Drive Southwest", "manager5", 0 );
CALL create_site("Inman Park", "30307", "", "david.smith", 1 );

CALL create_event("Piedmont Park", "Eastside Trail", "2019-02-04", "2019-02-05", 1, 0.00, 99999, "A combination of multi-use trail and linear greenspace, the Eastside Trail was the first finished section of the Atlanta BeltLine trail in the old rail corridor. The Eastside Trail, which was funded by a combination of public and private philanthropic sources, runs from the tip of Piedmont Park to Reynoldstown. More details at https://beltline.org/explore-atlanta-beltline-trails/eastside-trail/" );
CALL create_event("Inman Park", "Eastside Trail", "2019-02-04", "2019-02-05", 1, 0.00, 99999, "A combination of multi-use trail and linear greenspace, the Eastside Trail was the first finished section of the Atlanta BeltLine trail in the old rail corridor. The Eastside Trail, which was funded by a combination of public and private philanthropic sources, runs from the tip of Piedmont Park to Reynoldstown. More details at https://beltline.org/explore-atlanta-beltline-trails/eastside-trail/" );
CALL create_event("Inman Park", "Eastside Trail", "2019-03-01", "2019-03-02", 1, 0.00, 99999, "A combination of multi-use trail and linear greenspace, the Eastside Trail was the first finished section of the Atlanta BeltLine trail in the old rail corridor. The Eastside Trail, which was funded by a combination of public and private philanthropic sources, runs from the tip of Piedmont Park to Reynoldstown. More details at https://beltline.org/explore-atlanta-beltline-trails/eastside-trail/" );
CALL create_event("Historic Fourth Ward Park", "Eastside Trail", "2019-02-13", "2019-02-14", 1, 0.00, 99999, "A combination of multi-use trail and linear greenspace, the Eastside Trail was the first finished section of the Atlanta BeltLine trail in the old rail corridor. The Eastside Trail, which was funded by a combination of public and private philanthropic sources, runs from the tip of Piedmont Park to Reynoldstown. More details at https://beltline.org/explore-atlanta-beltline-trails/eastside-trail/" );
CALL create_event("Westview Cemetery", "Westside Trail", "2019-02-18", "2019-02-21", 1, 0.00, 99999, "The Westside Trail is a free amenity that offers a bicycle and pedestrian-safe corridor with a 14-foot-wide multi-use trail surrounded by mature trees and grasses thanks to Trees Atlanta’s Arboretum. With 16 points of entry, 14 of which will be ADA-accessible with ramp and stair systems, the trail provides numerous access points for people of all abilities. More details at: https://beltline.org/explore-atlanta-beltline-trails/westside-trail/" );
CALL create_event("Inman Park", "Bus Tour", "2019-02-01", "2019-02-02", 2, 25.00, 6, "The Atlanta BeltLine Partnership’s tour program operates with a natural gas-powered, ADA accessible tour bus funded through contributions from 10th & Monroe, LLC, SunTrust Bank Trusteed Foundations – Florence C. and Harry L. English Memorial Fund and Thomas Guy Woolford Charitable Trust, and AGL Resources" );
CALL create_event("Inman Park", "Bus Tour", "2019-02-08", "2019-02-10", 2, 25.00, 6, "The Atlanta BeltLine Partnership’s tour program operates with a natural gas-powered, ADA accessible tour bus funded through contributions from 10th & Monroe, LLC, SunTrust Bank Trusteed Foundations – Florence C. and Harry L. English Memorial Fund and Thomas Guy Woolford Charitable Trust, and AGL Resources" );
CALL create_event("Inman Park", "Private Bus Tour", "2019-02-01", "2019-02-02", 1, 40.00, 4, "Private tours are available most days, pending bus and tour guide availability. Private tours can accommodate up to 4 guests per tour, and are subject to a tour fee (nonprofit rates are available). As a nonprofit organization with limited resources, we are unable to offer free private tours. We thank you for your support and your understanding as we try to provide as many private group tours as possible. The Atlanta BeltLine Partnership’s tour program operates with a natural gas-powered, ADA accessible tour bus funded through contributions from 10th & Monroe, LLC, SunTrust Bank Trusteed Foundations – Florence C. and Harry L. English Memorial Fund and Thomas Guy Woolford Charitable Trust, and AGL Resources" );
CALL create_event("Inman Park", "Arboretum Walking Tour", "2019-02-08", "2019-02-11", 1, 5.00, 5, "Official Atlanta BeltLine Arboretum Walking Tours provide an up-close view of the Westside Trail and the Atlanta BeltLine Arboretum led by Trees Atlanta Docents. The one and a half hour tours step off at at 10am (Oct thru May), and 9am (June thru September). Departure for all tours is from Rose Circle Park near Brown Middle School. More details at: https://beltline.org/visit/atlanta-beltline-tours/#arboretum-walking" );
CALL create_event("Inman Park", "Official Atlanta BeltLine Bike Tour", "2019-02-09", "2019-02-14", 1, 5.00, 5, "These tours will include rest stops highlighting assets and points of interest along the Atlanta BeltLine. Staff will lead the rides, and each group will have a ride sweep to help with any unexpected mechanical difficulties." );

CALL create_transit("MARTA", "Blue", 2.00 );
CALL create_transit("BUS", "152", 2.00 );
CALL create_transit("BIKE", "Relay", 1.00 );

CALL connect_site("MARTA", "Blue", "Inman Park" );
CALL connect_site("MARTA", "Blue", "Piedmont Park" );
CALL connect_site("MARTA", "Blue", "Historic Fourth Ward Park" );
CALL connect_site("MARTA", "Blue", "Westview Cemetery" );
CALL connect_site("BUS", "152", "Inman Park" );
CALL connect_site("BUS", "152", "Piedmont Park" );
CALL connect_site("BUS", "152", "Historic Fourth Ward Park" );
CALL connect_site("BIKE", "Relay", "Piedmont Park" );
CALL connect_site("BIKE", "Relay", "Historic Fourth Ward Park" );

CALL take_transit("manager2", "Blue", "MARTA", "2019-03-20" );
CALL take_transit("manager2", "152", "BUS", "2019-03-20" );
CALL take_transit("manager3", "Relay", "BIKE", "2019-03-20" );
CALL take_transit("manager2", "Blue", "MARTA", "2019-03-21" );
CALL take_transit("maria.hernandez", "152", "BUS", "2019-03-20" );
CALL take_transit("maria.hernandez", "Relay", "BIKE", "2019-03-20" );
CALL take_transit("manager2", "Blue", "MARTA", "2019-03-22" );
CALL take_transit("maria.hernandez", "152", "BUS", "2019-03-22" );
CALL take_transit("mary.smith", "Relay", "BIKE", "2019-03-23" );
CALL take_transit("visitor1", "Blue", "MARTA", "2019-03-21" );

CALL assign_staff("Piedmont Park", "Eastside Trail", "2019-02-04", "michael.smith" );
CALL assign_staff("Piedmont Park", "Eastside Trail", "2019-02-04", "staff1" );
CALL assign_staff("Inman Park", "Eastside Trail", "2019-02-04", "robert.smith" );
CALL assign_staff("Inman Park", "Eastside Trail", "2019-02-04", "staff2" );
CALL assign_staff("Inman Park", "Eastside Trail", "2019-03-01", "staff1" );
CALL assign_staff("Historic Fourth Ward Park", "Eastside Trail", "2019-02-13", "michael.smith" );
CALL assign_staff("Westview Cemetery", "Westside Trail", "2019-02-18", "staff1" );
CALL assign_staff("Westview Cemetery", "Westside Trail", "2019-02-18", "staff3" );
CALL assign_staff("Inman Park", "Bus Tour", "2019-02-01", "michael.smith" );
CALL assign_staff("Inman Park", "Bus Tour", "2019-02-01", "staff2" );
CALL assign_staff("Inman Park", "Bus Tour", "2019-02-08", "robert.smith" );
CALL assign_staff("Inman Park", "Bus Tour", "2019-02-08", "michael.smith" );
CALL assign_staff("Inman Park", "Private Bus Tour", "2019-02-01", "robert.smith" );
CALL assign_staff("Inman Park", "Arboretum Walking Tour", "2019-02-08", "staff3" );
CALL assign_staff("Inman Park", "Official Atlanta BeltLine Bike Tour", "2019-02-09", "staff1" );

CALL log_event("Historic Fourth Ward Park", "Eastside Trail", "2019-02-13", "mary.smith", "2019-02-13" );
CALL log_event("Historic Fourth Ward Park", "Eastside Trail", "2019-02-13", "mary.smith", "2019-02-14" );
CALL log_event("Historic Fourth Ward Park", "Eastside Trail", "2019-02-13", "visitor1", "2019-02-14" );
CALL log_event("Inman Park", "Official Atlanta BeltLine Bike Tour", "2019-02-09", "visitor1", "2019-02-10" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "mary.smith", "2019-02-01" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "maria.garcia", "2019-02-02" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "manager2", "2019-02-02" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "manager4", "2019-02-01" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "manager5", "2019-02-02" );
CALL log_event("Inman Park", "Bus Tour", "2019-02-01", "staff2", "2019-02-02" );
CALL log_event("Inman Park", "Private Bus Tour", "2019-02-01", "mary.smith", "2019-02-01" );
CALL log_event("Inman Park", "Private Bus Tour", "2019-02-01", "mary.smith", "2019-02-02" );
CALL log_event("Inman Park", "Official Atlanta BeltLine Bike Tour", "2019-02-09", "mary.smith", "2019-02-10" );
CALL log_event("Inman Park", "Arboretum Walking Tour", "2019-02-08", "mary.smith", "2019-02-10" );
CALL log_event("Piedmont Park", "Eastside Trail", "2019-02-04", "mary.smith", "2019-02-04" );
CALL log_event("Westview Cemetery", "Westside Trail", "2019-02-18", "mary.smith", "2019-02-19" );
CALL log_event("Westview Cemetery", "Westside Trail", "2019-02-18", "visitor1", "2019-02-19" );

CALL log_site("Atlanta Beltline Center", "mary.smith", "2019-02-01" );
CALL log_site("Atlanta Beltline Center", "mary.smith", "2019-02-10" );
CALL log_site("Atlanta Beltline Center", "visitor1", "2019-02-13" );
CALL log_site("Atlanta Beltline Center", "visitor1", "2019-02-09" );
CALL log_site("Historic Fourth Ward Park", "mary.smith", "2019-02-02" );
CALL log_site("Historic Fourth Ward Park", "visitor1", "2019-02-11" );
CALL log_site("Inman Park", "mary.smith", "2019-02-01" );
CALL log_site("Inman Park", "mary.smith", "2019-02-02" );
CALL log_site("Inman Park", "mary.smith", "2019-02-03" );
CALL log_site("Inman Park", "visitor1", "2019-02-01" );
CALL log_site("Piedmont Park", "mary.smith", "2019-02-02" );
CALL log_site("Piedmont Park", "visitor1", "2019-02-11" );
CALL log_site("Piedmont Park", "visitor1", "2019-02-01" );
CALL log_site("Westview Cemetery", "visitor1", "2019-02-06" );